/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sniperUI;

import com.toedter.calendar.JDateChooser;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Map;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sniperModel.DoctorDirectory;
import sniperModel.HospitalDirectory;
import sniperModel.Patient;
import sniperModel.PatientDirectory;
import sniperModel.Person;
import sniperModel.PersonDirectory;

/**
 *
 * @author ganes
 */
public class CreatePatientUI extends javax.swing.JPanel {

    /**
     * Creates new form CreatePatientUI
     */
    PersonDirectory pDir ;
    HospitalDirectory hDir;
    PatientDirectory patDir;
    DoctorDirectory dDir;
    String userName;
    
    int id, patId, age, height ;
    String fName = null ,lName = null , pMail = null, pMob = null , pHouse = null, city =null,community =null, date =null, curdate = null , hos = null;
    Double weight;
    ArrayList<String> hosName =  new ArrayList();
    
    public CreatePatientUI(PersonDirectory p, HospitalDirectory h, PatientDirectory pat, DoctorDirectory d , String u) {
        initComponents();
        this.pDir = p;
        this.hDir = h;
        this.patDir = pat;
        this.userName = u;
        this.dDir = d;
        displayPersonDetails(this.pDir, this.userName);
    }
    
    public void clear(){
        Tage.setText("");
        Tht.setText("");
        Twt.setText("");
        Tdate.setCalendar(null);
        
    }
     
    public void displayPersonDetails(PersonDirectory p, String un){
        try{
        if(p.isEmpty()){
            JOptionPane.showMessageDialog(this, "Person Directory is empty. Please add Person Data!!");
        }
        else{
            Person pt = this.pDir.getPersonByUserName(un) ;
            
            fn.setText(pt.getfName());
            ln.setText(pt.getlName());
            pmobile.setText(pt.getPmob());
            pmail.setText(pt.getPmail());
            pid.setText(pt.getPid()+"");
            ph.setText(pt.getHouse());
            pcity.setText(pt.getCity());
            pcom.setText(pt.getCom());
            
            pid.setEditable(false);
            fn.setEditable(false);
            ln.setEditable(false);
            pmail.setEditable(false);
            pmobile.setEditable(false);
            ph.setEditable(false);
            pcity.setEditable(false);
            pcom.setEditable(false);
            
        }
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, "Something went wrong. Please try again");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pid = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fn = new javax.swing.JTextField();
        ln = new javax.swing.JTextField();
        pmobile = new javax.swing.JTextField();
        pmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ph = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pcity = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pcom = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Tage = new javax.swing.JTextField();
        Tht = new javax.swing.JTextField();
        Twt = new javax.swing.JTextField();
        Tdate = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        hosList = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        BookApp = new javax.swing.JButton();
        SeeByCity = new javax.swing.JButton();
        SeeByComm = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        CityAndCom = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 51, 51));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel12.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel12.setText("ID");

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel9.setText("House");

        pid.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel10.setText("City");

        jLabel11.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel11.setText("Community");

        fn.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N

        ln.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N

        pmobile.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N

        pmail.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel5.setText("First Name");

        ph.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel6.setText("Last Name");

        pcity.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel7.setText("Mobile Number");

        pcom.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel8.setText("Email ID");

        jLabel13.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel13.setText("Age");

        jLabel14.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel14.setText("Height (in cms)");

        jLabel15.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel15.setText("Weight (in kgs)");

        Tage.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N

        Tht.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N

        Twt.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N

        Tdate.setDateFormatString("dd-MM-yyyy");
        Tdate.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel16.setText("Date ");

        jLabel17.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel17.setText("Hospital");

        hosList.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        hosList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hosListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Twt, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(hosList, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Tht, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pcom, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ln, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pmobile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Tage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Tdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ph, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                    .addComponent(pcity)
                                    .addComponent(pid))))
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel15, jLabel5, jLabel6, jLabel7, jLabel8});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(pid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(ph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(pmobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(pcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(pmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(pcom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(Tage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(Twt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(hosList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tht, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Tage, Tht, Twt});

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        BookApp.setFont(new java.awt.Font("Cambria", 3, 12)); // NOI18N
        BookApp.setText("Book Appoinment");
        BookApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookAppActionPerformed(evt);
            }
        });

        SeeByCity.setFont(new java.awt.Font("Cambria", 3, 12)); // NOI18N
        SeeByCity.setText("See by City");
        SeeByCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeeByCityActionPerformed(evt);
            }
        });

        SeeByComm.setFont(new java.awt.Font("Cambria", 3, 12)); // NOI18N
        SeeByComm.setText("See by Community");
        SeeByComm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeeByCommActionPerformed(evt);
            }
        });

        reset.setFont(new java.awt.Font("Cambria", 3, 12)); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        CityAndCom.setFont(new java.awt.Font("Cambria", 3, 12)); // NOI18N
        CityAndCom.setText("Edit City and Community");
        CityAndCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityAndComActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BookApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SeeByComm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SeeByCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CityAndCom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(SeeByComm)
                .addGap(18, 18, 18)
                .addComponent(SeeByCity)
                .addGap(18, 18, 18)
                .addComponent(BookApp)
                .addGap(26, 26, 26)
                .addComponent(reset)
                .addGap(18, 18, 18)
                .addComponent(CityAndCom)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 623, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BookAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookAppActionPerformed
        // TODO add your handling code here:
        
              //Age Validation
               if(Tage.getText().isEmpty()) 
               {
                    JOptionPane.showMessageDialog(BookApp, "Age is required");
                    return;
                }else 
               {
                    String nameRegex = "^(0?[1-9]|[1-9][0-9]|[1][1-9][1-9]|200)$";
                    Pattern namePattern = Pattern.compile(nameRegex);
                    Matcher nameMatcher = namePattern.matcher(Tage.getText());

                    if(!nameMatcher.matches())
                    {
                        JOptionPane.showMessageDialog(BookApp, "Please enter valid Age");
                        return;
                    }
               }
               //Weight Validation
               if(Twt.getText().isEmpty()) 
               {
                    JOptionPane.showMessageDialog(BookApp, "Weight is required");
                    return;
                }
               else 
               {
                    String nameRegex = "^[1-9]\\d*$";
                    Pattern namePattern = Pattern.compile(nameRegex);
                    Matcher nameMatcher = namePattern.matcher(Twt.getText());

                    if(!nameMatcher.matches())
                    {
                        JOptionPane.showMessageDialog(BookApp, "Please enter valid Weight");
                        return;
                    }
               } 
               
               //Height Validation
                if(Tht.getText().isEmpty()) 
               {
                    JOptionPane.showMessageDialog(BookApp, "Height is required");
                    return;
                }
               else 
               {
                    String nameRegex = "^[1-9]\\d*$";
                    Pattern namePattern = Pattern.compile(nameRegex);
                    Matcher nameMatcher = namePattern.matcher(Tht.getText());

                    if(!nameMatcher.matches())
                    {
                        JOptionPane.showMessageDialog(BookApp, "Please enter valid Height");
                        return;
                    }
               }               
               
               
        try{
        SimpleDateFormat vlf = new SimpleDateFormat("dd-MM-yyyy");
        String sdt= vlf.format(Tdate.getDate());
        Date curdt = new Date();
        String cd = vlf.format(curdt);
        
        Date sd = vlf.parse(sdt);
        Date td = vlf.parse(cd);
        
        System.out.println("selected date : "+sd);
        System.out.println("Current date : "+td);
        System.out.println("sd is before cur : "+sd.before(td));
        
        if(this.hDir.isEmpty()){
            JOptionPane.showMessageDialog(this, "Hospital Directory is empty. Please add Hospital Details!!");
        }
        else
        if(hosList.getSelectedItem()== null){
            JOptionPane.showMessageDialog(this, "Hospital is not selected. Please select Hospital!!");
        }
        else
        if(sd.before(td)){
            JOptionPane.showMessageDialog(this, "Past Date is selected. Please try again with present or future date!!");
        }
        else{
            date = sdt;
            id = Integer.parseInt(pid.getText());
            Person p = this.pDir.getPerson(id);
            String city= pcity.getText();
            String commu= pcom.getText();
            p.setCity(city);
            p.setCom(commu);
            age = Integer.parseInt(Tage.getText());
            height = Integer.parseInt(Tht.getText());
            weight = Double.parseDouble(Twt.getText());
            hos = hosList.getSelectedItem().toString();
            System.out.println(hosList.getSelectedItem().toString());
            
            Patient pat = new Patient();
            pat.setId(id);
            pat.setPer(p);
            pat.setAge(age);
            pat.setHeight(height);
            pat.setWeight(weight);
            pat.setDate(date);
            pat.setHospital(hos);
            
            this.patDir.addPatient(id, pat);
            this.patDir.displayPatientDir();
            clear();
            this.pDir.addPerson(id, p);
        }
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Something went wrong. Please Try Agian!!");
        }
    }//GEN-LAST:event_BookAppActionPerformed

    private void SeeByCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeeByCityActionPerformed
        // TODO add your handling code here:
        hosList.removeAllItems();
        if(this.hDir.isEmpty()){
            JOptionPane.showMessageDialog(this, "Hospital Directory is empty. Please add Hospital Details!!");
        }
        else
        if( pcity.getText().equals("")){
            JOptionPane.showMessageDialog(this, "City Field is Empty. Please enter data for City!!");
        }
        else{  System.out.println(pcity.getText());
            city = pcity.getText();
            hosName = this.hDir.getHospitalNamesByCity(city);
            if(hosName.isEmpty()){
                JOptionPane.showMessageDialog(this, "There is no Hospital near by your City!!");
            }
            else{
            for(String s : hosName){
                hosList.addItem(s);
             }
            }
        }
    }//GEN-LAST:event_SeeByCityActionPerformed

    private void SeeByCommActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeeByCommActionPerformed
        // TODO add your handling code here:
        hosList.removeAllItems();
        if(this.hDir.isEmpty()){
            JOptionPane.showMessageDialog(this, "Hospital Directory is empty. Please add Hospital Details!!");
        }
        else
        if( pcom.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Community Field is Empty. Please enter data for Community!!");
        }
        else{
            System.out.println(pcom.getText());
            community = pcom.getText();
            hosName = this.hDir.getHospitalNamesByCommunity(community);
            if(hosName.isEmpty()){
                JOptionPane.showMessageDialog(this, "There is no Hospital near by your Community!!");
            }
            else{
            for(String s : hosName){
                hosList.addItem(s);
             }
            }
        }
    }//GEN-LAST:event_SeeByCommActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_resetActionPerformed

    private void CityAndComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityAndComActionPerformed
        // TODO add your handling code here:
        pcity.setEditable(true);
        pcom.setEditable(true);
    }//GEN-LAST:event_CityAndComActionPerformed

    private void hosListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hosListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hosListActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookApp;
    private javax.swing.JButton CityAndCom;
    private javax.swing.JButton SeeByCity;
    private javax.swing.JButton SeeByComm;
    private javax.swing.JTextField Tage;
    private com.toedter.calendar.JDateChooser Tdate;
    private javax.swing.JTextField Tht;
    private javax.swing.JTextField Twt;
    private javax.swing.JTextField fn;
    private javax.swing.JComboBox<String> hosList;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField ln;
    private javax.swing.JTextField pcity;
    private javax.swing.JTextField pcom;
    private javax.swing.JTextField ph;
    private javax.swing.JTextField pid;
    private javax.swing.JTextField pmail;
    private javax.swing.JTextField pmobile;
    private javax.swing.JButton reset;
    // End of variables declaration//GEN-END:variables
}
