/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sniperUI;

import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sniperModel.Patient;
import sniperModel.PatientDirectory;

/**
 *
 * @author ganes
 */
public class HadViewPatient extends javax.swing.JPanel {

    /**
     * Creates new form HadViewPatient
     */
    PatientDirectory patDir;
    public HadViewPatient(PatientDirectory p) {
        initComponents();
        this.patDir = p;
        displayPatients(this.patDir);
    }
    
    public void displayPatients(PatientDirectory p){
         try{
        if(p.isEmpty()){
            JOptionPane.showMessageDialog(this, "No Patient are their. Please add Patient!!");
        }
        else{
            DefaultTableModel pat = (DefaultTableModel) PatTable.getModel();
            
            Map<Integer,Patient> pm = p.getPatDir();
            Set<Map.Entry<Integer,Patient>> patList = pm.entrySet();
        
            for(Map.Entry<Integer,Patient> e : patList){
                
                Object[] sd = new Object[5];  
                Patient p1 = e.getValue();
                /*
                id person name, age, height, weight;
                */
                sd[0] = (int) e.getKey();
                sd[1] = p1.getPersonName();
                sd[2] = p1.getAge();
                sd[3] = p1.getHeight();
                sd[4] = p1.getWeight();
                pat.addRow(sd);                                
            }
        }
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, "Something went wrong. Please try again");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PatTable = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        PatTable.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        PatTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Age", "Height", "Wieght"
            }
        ));
        jScrollPane1.setViewportView(PatTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable PatTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
