/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sniperUI;

import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sniperModel.Patient;
import sniperModel.PatientDirectory;

/**
 *
 * @author ganes
 */
public class HadViewApp extends javax.swing.JPanel {

    /**
     * Creates new form HadViewApp
     */
    PatientDirectory patDir;
    
    public HadViewApp(PatientDirectory p) {
        initComponents();
        this.patDir = p;
        displayAppointments(this.patDir);
    }
    
    public void displayAppointments(PatientDirectory p){
         try{
        if(p.isEmpty()){
            JOptionPane.showMessageDialog(this, "Their is no Appointment Today.");
        }
        else{
            DefaultTableModel pat = (DefaultTableModel) AppTable.getModel();
            
            Map<Integer,Patient> pm = p.getPatDir();
            Set<Map.Entry<Integer,Patient>> patList = pm.entrySet();
        
            for(Map.Entry<Integer,Patient> e : patList){
                
                Object[] sd = new Object[4];  
                Patient p1 = e.getValue();
                /*
                id person name, age, height, weight;
                */
                sd[0] = (int) e.getKey();
                sd[1] = p1.getPersonName();
                sd[2] = p1.getDate();
                sd[3] = p1.getHospital();
                pat.addRow(sd);                                
            }
        }
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, "Something went wrong. Please try again");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AppTable = new javax.swing.JTable();
        Delete = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        AppTable.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        AppTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Date", "Hospital"
            }
        ));
        jScrollPane1.setViewportView(AppTable);

        Delete.setFont(new java.awt.Font("Cambria", 3, 14)); // NOI18N
        Delete.setText("Delete Appointment");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Delete)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Delete)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        try{
        DefaultTableModel doc = (DefaultTableModel) AppTable.getModel();
        
        if(AppTable.getSelectedRowCount() == 1){
            
            int pid = Integer.parseInt(doc.getValueAt(AppTable.getSelectedRow(), 0).toString());
            this.patDir.removeById(pid);
            doc.removeRow(AppTable.getSelectedRow());
            
            JOptionPane.showMessageDialog(this, "Record is Successfully Deleted");
        }
        else{
            if(AppTable.getRowCount()==0){
                JOptionPane.showMessageDialog(this, "Table is Empty. Please add data!");
            }
            else{
                JOptionPane.showMessageDialog(this, "Please select single row to delete!");
            }
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Problem occured while deleting. Please try again!!");
        }
               
    }//GEN-LAST:event_DeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AppTable;
    private javax.swing.JButton Delete;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
