/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sniperUI;

import javax.swing.JOptionPane;
import sniperModel.CommunityDirectory;
import sniperModel.DoctorDirectory;
import sniperModel.EncounterDirectory;
import sniperModel.HospitalDirectory;
import sniperModel.PatientDirectory;
import sniperModel.PersonDirectory;

/**
 *
 * @author ganes
 */
public class LoginMainFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginMainFrame
     */
    DoctorDirectory dDir;
    PersonDirectory pDir;
    HospitalDirectory hDir;
    CommunityDirectory cDir;
    PatientDirectory patDir;
    EncounterDirectory endir;
    
    String un =null, pass = null;
    int urole;
    
    public void clear(){
        Tun.setText("");
        Tp.setText("");
        Cur.setSelectedIndex(0);
    }
    
    public LoginMainFrame(DoctorDirectory d, PersonDirectory p, HospitalDirectory h, CommunityDirectory c, PatientDirectory pat, EncounterDirectory e) {
        initComponents();
        this.dDir = d;
        this.pDir = p;
        this.hDir = h;
        this.cDir = c;
        this.patDir = pat;
        this.endir = e;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginDesk = new javax.swing.JDesktopPane();
        Login = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Cur = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Tun = new javax.swing.JTextField();
        Tp = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        NewPat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 153, 255));

        LoginDesk.setBackground(new java.awt.Color(21, 65, 195));
        LoginDesk.setForeground(new java.awt.Color(0, 153, 255));

        Login.setFont(new java.awt.Font("Cambria", 3, 16)); // NOI18N
        Login.setText("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });

        Exit.setFont(new java.awt.Font("Cambria", 3, 16)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/snehagiranje/Downloads/trend-in-healthcare-jobs.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hospital Management System");

        Cur.setBackground(new java.awt.Color(204, 204, 204));
        Cur.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Cur.setForeground(new java.awt.Color(255, 255, 255));
        Cur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "System Admin", "Hospital Admin", "Community Admin", "Doctor", "Patient" }));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("User Name");

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");

        Tun.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N

        Tp.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("User Role");

        jLabel7.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Login");

        NewPat.setFont(new java.awt.Font("Cambria", 3, 16)); // NOI18N
        NewPat.setText("New Patient Registration");
        NewPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewPatActionPerformed(evt);
            }
        });

        LoginDesk.setLayer(Login, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LoginDesk.setLayer(Exit, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LoginDesk.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LoginDesk.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LoginDesk.setLayer(Cur, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LoginDesk.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LoginDesk.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LoginDesk.setLayer(Tun, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LoginDesk.setLayer(Tp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LoginDesk.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LoginDesk.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LoginDesk.setLayer(NewPat, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout LoginDeskLayout = new javax.swing.GroupLayout(LoginDesk);
        LoginDesk.setLayout(LoginDeskLayout);
        LoginDeskLayout.setHorizontalGroup(
            LoginDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginDeskLayout.createSequentialGroup()
                .addGroup(LoginDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginDeskLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(LoginDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LoginDeskLayout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(LoginDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(LoginDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, LoginDeskLayout.createSequentialGroup()
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(Tp))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, LoginDeskLayout.createSequentialGroup()
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(Tun, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(LoginDeskLayout.createSequentialGroup()
                                        .addGroup(LoginDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Login))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(LoginDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Exit)
                                            .addComponent(Cur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(NewPat, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(LoginDeskLayout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(LoginDeskLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 111, Short.MAX_VALUE))
        );
        LoginDeskLayout.setVerticalGroup(
            LoginDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginDeskLayout.createSequentialGroup()
                .addGroup(LoginDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginDeskLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LoginDeskLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel7)
                        .addGap(60, 60, 60)
                        .addGroup(LoginDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Tun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(LoginDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Tp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(LoginDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Cur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71)
                        .addGroup(LoginDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Login)
                            .addComponent(Exit))
                        .addGap(30, 30, 30)
                        .addComponent(NewPat)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LoginDesk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginDesk)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
        
        pass = new String(Tp.getPassword());
        un = Tun.getText();
        urole = Cur.getSelectedIndex();
        
        
        if( un.equals("")){
            JOptionPane.showMessageDialog(this, "User Name is not entered. Please Add User name and try again");
        }
        else
        if( pass.equals("")){
            JOptionPane.showMessageDialog(this, "Password is not entered. Please enter password and try again");
        }
        else
        if( urole == 0 ){
            JOptionPane.showMessageDialog(this, "User Role is not Selected. Please select user role and try again");
        }
        else{
            
            if(urole == 1){
                if( un.equals("SysAdmin") && pass.equals("sneha@123")){
                    SystemAdminUI sa = new SystemAdminUI(this.dDir,this.pDir,this.hDir,this.cDir);
                    LoginDesk.add(sa);
                    sa.setVisible(true);
                }
                else{
                    JOptionPane.showMessageDialog(this, "Credentail is invalid. Please enter valid credential and try again");
                }
            }
            else
            if(urole == 2){
                if(un.equals("HosAdmin") && pass.equals("sneha@123")){
                    HospitalAdminUI had = new HospitalAdminUI(this.patDir);
                    LoginDesk.add(had);
                    had.setVisible(true);
                }
                else{
                    JOptionPane.showMessageDialog(this, "Credentail is invalid. Please enter valid credential and try again");
                }
            }
            else
            if(urole == 3){
                if(un.equals("ComAdmin") && pass.equals("sneha@123")){
                    CommunityCreateUI had = new CommunityCreateUI(this.cDir);
                    LoginDesk.add(had);
                    had.setVisible(true);
                }
                else{
                    JOptionPane.showMessageDialog(this, "Credentail is invalid. Please enter valid credential and try again");
                }
                
            }
            else
            if(urole == 4){
                if(this.dDir.checkPassword(un, pass)){
                    String hn = this.dDir.getHospitalName(un);
                    if(hn != null){
                    DoctorVisitUI dad = new DoctorVisitUI(this.patDir,this.endir, hn );
                    LoginDesk.add(dad);
                    dad.setVisible(true);
                    }
                    else
                    JOptionPane.showMessageDialog(this, "Hospital is not mapped. Please contact System Admin for more Details");
                }
                else{
                    JOptionPane.showMessageDialog(this, "Credentail is invalid. Please enter valid credential and try again");
                }                
            }
            else
            if(urole == 5){
                if(this.pDir.checkPassword(un, pass)){
                    PatientUI pat = new PatientUI(this.dDir,this.pDir,this.hDir,this.cDir, this.patDir, un);
                    LoginDesk.add(pat);
                    pat.setVisible(true);
                }
                else{
                    JOptionPane.showMessageDialog(this, "Credentail is invalid. Please enter valid credential and try again");
                } 
            }
        }
        clear();
    }//GEN-LAST:event_LoginActionPerformed

    private void NewPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewPatActionPerformed
        // TODO add your handling code here:
        NewPatientUI had = new NewPatientUI(this.pDir,this.cDir);
        LoginDesk.add(had);
        had.setVisible(true);
    }//GEN-LAST:event_NewPatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DoctorDirectory d = new DoctorDirectory();
                PersonDirectory p = new PersonDirectory();
                HospitalDirectory h =  new HospitalDirectory();
                CommunityDirectory c = new CommunityDirectory();
                PatientDirectory pat = new PatientDirectory();
                EncounterDirectory e = new EncounterDirectory();
                new LoginMainFrame(d,p,h,c,pat,e).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cur;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Login;
    private javax.swing.JDesktopPane LoginDesk;
    private javax.swing.JButton NewPat;
    private javax.swing.JPasswordField Tp;
    private javax.swing.JTextField Tun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
